
zone {
    name = "zone-1"
    auth_group = eva-zone-1

    key_control {
        algs = all
        files {
            path = /chroot/kms/keys
            filter_regex = '.+?(%I|%E|%I%E)?\.pem'
            scan_interval = 10
        }
    }

    manager {
        user = eva-zone-1

        log {
            device = "syslog://?facility=local5&levels=all:info&annotate=topic,level,align"
        }
    }

    agent {
        log {
            device = "syslog://?facility=local5&levels=all:info;key-ctrl:debug&annotate=topic,level,align"
        }
    }
}
